#!/usr/bin/env node
// Dev-only: rebuilds js/icons.js — the Phosphor duotone icons that the word topics in data/*.js name in `icon`.
// Run: node tools/icons.js            (downloads @phosphor-icons/core with `npm pack`)
//      node tools/icons.js <core dir>  (an unpacked @phosphor-icons/core, e.g. node_modules/@phosphor-icons/core)
'use strict';
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const { loadSite } = require('./validate-content.js');

const VERSION = '2.1.1';
const root = path.join(__dirname, '..');
const out = path.join(root, 'js', 'icons.js');

function coreDir() {
  if (process.argv[2]) return path.resolve(process.argv[2]);
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'phosphor-'));
  const tgz = execFileSync('npm', ['pack', '@phosphor-icons/core@' + VERSION, '--silent', '--pack-destination', tmp], { encoding: 'utf8' }).trim();
  execFileSync('tar', ['xzf', path.join(tmp, tgz), '-C', tmp]);
  return path.join(tmp, 'package');
}

// '<svg …><path d="…" opacity="0.2"/><path d="…"/></svg>' → [['…', 0.2], ['…']]
function paths(svg, name) {
  const inner = svg.replace(/^<svg[^>]*>|<\/svg>\s*$/g, '');
  const tags = inner.match(/<[a-z]+[^>]*\/>/g) || [];
  if (tags.join('') !== inner) throw new Error(name + ': unexpected markup');
  return tags.map((tag) => {
    const d = (tag.match(/^<path d="([^"]+)"/) || [])[1];
    if (!d) throw new Error(name + ': only <path d> is supported, got ' + tag.slice(0, 40));
    const op = (tag.match(/ opacity="([\d.]+)"/) || [])[1];
    return op ? [d, Number(op)] : [d];
  });
}

const ECA = loadSite(root).ECA;
const names = [...new Set(ECA.data.levels().flatMap((l) => ECA.data.vocab(l.id).map((t) => t.icon)))].sort();
const dir = path.join(coreDir(), 'assets', 'duotone');
const icons = names.map((name) => {
  const file = path.join(dir, name + '-duotone.svg');
  if (!fs.existsSync(file)) throw new Error(`no Phosphor icon «${name}» — names: https://phosphoricons.com`);
  return '    ' + JSON.stringify(name) + ': ' + JSON.stringify(paths(fs.readFileSync(file, 'utf8'), name));
});

fs.writeFileSync(out, `// Generated by tools/icons.js — do not edit by hand.
// Phosphor Icons, duotone weight (https://phosphoricons.com), MIT License, Copyright (c) 2023 Phosphor Icons.
// name → paths in a 256×256 box: [d] or [d, opacity]; drawn with currentColor by ECA.ui.topicIcon.
(function (root) {
  'use strict';
  var ECA = (root.ECA = root.ECA || {});
  ECA.icons = {
${icons.join(',\n')}
  };
})(typeof window !== 'undefined' ? window : globalThis);
`);
console.log(`js/icons.js: ${names.length} icons`);
